# Generated by Django 4.2.6 on 2023-11-02 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id_film', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('stars_journalist', models.CharField(blank=True, max_length=50, null=True)),
                ('stars_spectators', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('reference', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'film',
            },
        ),
        migrations.CreateModel(
            name='SpectatorCritics',
            fields=[
                ('id_spectator_critics', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=50, null=True)),
                ('stars', models.CharField(blank=True, max_length=50, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('id_film', models.ForeignKey(db_column='id_film', on_delete=django.db.models.deletion.DO_NOTHING, to='api.film')),
            ],
            options={
                'db_table': 'spectator_critics',
            },
        ),
        migrations.CreateModel(
            name='ModelDistilbertBmcss',
            fields=[
                ('id_distilbert', models.AutoField(primary_key=True, serialize=False)),
                ('positive', models.CharField(blank=True, max_length=50, null=True)),
                ('negative', models.CharField(blank=True, max_length=50, null=True)),
                ('neutral', models.CharField(blank=True, max_length=50, null=True)),
                ('id_spectator_critics', models.ForeignKey(db_column='id_spectator_critics', on_delete=django.db.models.deletion.DO_NOTHING, to='api.spectatorcritics')),
            ],
            options={
                'db_table': 'model_distilbert_bmcss',
            },
        ),
        migrations.CreateModel(
            name='ModelBertBmus',
            fields=[
                ('id_bert', models.AutoField(primary_key=True, serialize=False)),
                ('five_stars', models.CharField(blank=True, max_length=50, null=True)),
                ('four_stars', models.CharField(blank=True, max_length=50, null=True)),
                ('three_stars', models.CharField(blank=True, max_length=50, null=True)),
                ('two_stars', models.CharField(blank=True, max_length=50, null=True)),
                ('one_stars', models.CharField(blank=True, max_length=50, null=True)),
                ('id_spectator_critics', models.ForeignKey(db_column='id_spectator_critics', on_delete=django.db.models.deletion.DO_NOTHING, to='api.spectatorcritics')),
            ],
            options={
                'db_table': 'model_bert_bmus',
            },
        ),
        migrations.CreateModel(
            name='JournalistCritics',
            fields=[
                ('id_journalist_critics', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=50, null=True)),
                ('stars', models.CharField(blank=True, max_length=50, null=True)),
                ('id_film', models.ForeignKey(db_column='id_film', on_delete=django.db.models.deletion.DO_NOTHING, to='api.film')),
            ],
            options={
                'db_table': 'journalist_critics',
            },
        ),
    ]
