# Generated by Django 4.2.6 on 2023-11-03 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_journalistcritics_id_film_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalistcritics',
            name='id_film',
            field=models.ForeignKey(db_column='id_film', on_delete=django.db.models.deletion.DO_NOTHING, to='api.film'),
        ),
        migrations.AlterField(
            model_name='spectatorcritics',
            name='id_film',
            field=models.ForeignKey(db_column='id_film', on_delete=django.db.models.deletion.DO_NOTHING, to='api.film'),
        ),
    ]
