# Generated by Django 4.2.6 on 2023-11-03 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_djangomigrations_remove_history_id_bert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='id_history',
            field=models.ForeignKey(blank=True, db_column='id_history', on_delete=django.db.models.deletion.DO_NOTHING, to='api.history'),
        ),
        migrations.AlterField(
            model_name='modelbertbmus',
            name='id_history',
            field=models.ForeignKey(blank=True, db_column='id_history', on_delete=django.db.models.deletion.DO_NOTHING, to='api.history'),
        ),
        migrations.AlterField(
            model_name='modeldistilbertbmcss',
            name='id_history',
            field=models.ForeignKey(blank=True, db_column='id_history', on_delete=django.db.models.deletion.DO_NOTHING, to='api.history'),
        ),
        migrations.AlterField(
            model_name='spectatorcritics',
            name='id_history',
            field=models.ForeignKey(blank=True, db_column='id_history', on_delete=django.db.models.deletion.DO_NOTHING, to='api.history'),
        ),
    ]
